#====================#
#=== PACKAGE INFO ===#

[package]
  name = "lunex"
  description = "Blazingly fast retained UI layout engine for Bevy ECS"
  edition = "2024"

#===============================#
#=== DEPENDENCIES & FEATURES ===#

[dependencies]

  # GAME ENGINE
  bevy = { workspace = true }
  bevy_rich_text3d = { version = "0.3", optional = true }

  # RUST MISCELLANEOUS
  radsort = "0.1.1"
  colored = "3.0.0"

[features]

  default = [
    "text3d"
  ]

  text3d = ["dep:bevy_rich_text3d"]
