[package]
name = "sup"
description = "support"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
bevyx = { path = "../bevyx" }
sim = { path = "../sim" }
base = { path = "../base" }

bevy = { workspace = true }
