[package]
name = "sup"
description = "support"
version = "0.1.0"
edition = "2021"

[dependencies]
bevyx = { path = "../bevyx" }
sim = { path = "../sim" }
base = { path = "../base" }

bevy = { workspace = true }
