[package]
name = "flatland"
version = "0.1.0"
authors = ["Scott Checko <schecko@sfu.ca>"]
edition = "2018"
build = "build.rs"

[dependencies]
glutin = "0.22.0-alpha5"

[build-dependencies]
gl_generator = "0.13"
