[package]
name = "cim"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", features = ["default", "bevy_dev_tools"] }

# Enable optimizations for dependencies
[profile.dev.package."*"]
opt-level = 3
