[package]
name = "bevyx"
description = "Bevy Extensions"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
bevy = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
